config/routes.rb
Rails.application.routes.draw do
  resources :post_types
  resources :categories
  resources :categories_translations
  resources :article_types_translations
  resources :article_types
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    extend Mobility
    translates :name, locale_accessors: [:en, :ja]
end
#rails generate mobility:translations article name:string --backend=table

app/models/categories_translation.rb
class CategoriesTranslation < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :article_type
end

app/models/post_type.rb
class PostType < ApplicationRecord
    # extend Mobility
    # translates :name, backend: 'post_type_translations.rb'
    
    
   
    extend Mobility
    translates :name, fallbacks: { en: :ja, ja: :en }

end


PostType.new(name_en: "foo").name_ja

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = ArticleType.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:image, :sub_categories, :article_type_id)
    end
end

app/controllers/categories_translations_controller.rb
class CategoriesTranslationsController < ApplicationController
end

app/controllers/post_types_controller.rb
class PostTypesController < ApplicationController
  before_action :set_post_type, only: [:show, :edit, :update, :destroy]

  # GET /post_types
  # GET /post_types.json
  def index
    @post_types = PostType.all
  end

  # GET /post_types/1
  # GET /post_types/1.json
  def show
  end

  # GET /post_types/new
  def new
    @post_type = PostType.new
  end

  # GET /post_types/1/edit
  def edit
  end

  # POST /post_types
  # POST /post_types.json
  def create
    @post_type = PostType.new(post_type_params)

    respond_to do |format|
      if @post_type.save
        format.html { redirect_to @post_type, notice: 'Post type was successfully created.' }
        format.json { render :show, status: :created, location: @post_type }
      else
        format.html { render :new }
        format.json { render json: @post_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_types/1
  # PATCH/PUT /post_types/1.json
  def update
    respond_to do |format|
      if @post_type.update(post_type_params)
        format.html { redirect_to @post_type, notice: 'Post type was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_type }
      else
        format.html { render :edit }
        format.json { render json: @post_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_types/1
  # DELETE /post_types/1.json
  def destroy
    @post_type.destroy
    respond_to do |format|
      format.html { redirect_to post_types_url, notice: 'Post type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_type
      @post_type = PostType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_type_params
      params.require(:post_type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/categories_translations_helper.rb
module CategoriesTranslationsHelper
end

app/helpers/post_types_helper.rb
module PostTypesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.name %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :sub_categories %>
    <%= form.number_field :sub_categories %>
  </div>

  <div class="field">
    <%= form.label :article_type_id %>
    <%= form.text_field :article_type_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Sub categories</th>
      <th>Article type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.image %></td>
        <td><%= category.sub_categories %></td>
        <td><%= category.article_type_id %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @category.image %>
</p>

<p>
  <strong>Sub categories:</strong>
  <%= @category.sub_categories %>
</p>

<p>
  <strong>Article type:</strong>
  <%= @category.article_type_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Articles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post_types/_form.html.erb
<%= form_with(model: post_type) do |form| %>
  <% if post_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_type.errors.count, "error") %> prohibited this post_type from being saved:</h2>

      <ul>
        <% post_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_types/edit.html.erb
<h1>Editing Post Type</h1>

<%= render 'form', post_type: @post_type %>

<%= link_to 'Show', @post_type %> |
<%= link_to 'Back', post_types_path %>

app/views/post_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_types.each do |post_type| %>
      <tr>
        <td><%= post_type.name %></td>
        <td><%= link_to 'Show', post_type %></td>
        <td><%= link_to 'Edit', edit_post_type_path(post_type) %></td>
        <td><%= link_to 'Destroy', post_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post Type', new_post_type_path %>

app/views/post_types/new.html.erb
<h1>New Post Type</h1>

<%= render 'form', post_type: @post_type %>

<%= link_to 'Back', post_types_path %>

app/views/post_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post_type.name %>
</p>

<%= link_to 'Edit', edit_post_type_path(@post_type) %> |
<%= link_to 'Back', post_types_path %>